meta_product_name: "5crewed"
meta_title: "5crewed.com"
meta_description: "Don't get confused get 5crewed"
meta_image: "icon.png"                       # should exist in `app/assets/images/`
twitter_account: "@5crewed"
